version: "3.8"
services:
  frontend:
    image: fbck-frontend
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: fbck-backend
    build: ./backend
    ports:
      - "4001:4001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge