# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd backend
          npm ci
          cd ../frontend
          npm ci

      # - name: Format Code with Prettier (Backend)
      #   uses: prettier/action@v3
      #   with:
      #     args: --write .
      #     working-directory: ./backend

      - name: Lint Code with ESLint (Backend)
        run: |
          cd backend
          npm run lint

      - name: Run E2E Tests (Backend, if present)
        run: |
          cd backend
          npm run e2e-test || echo "E2E tests not found"

      - name: Build the Backend Application
        run: |
          cd backend
          npm run build

      - name: Build the Frontend Application
        run: |
          cd frontend
          npm run build
