# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test Action

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 24.x] # Consider a broader range based on your project

    steps:
      - uses: actions/checkout@v4

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          FILE_PATTERN: '*.js'
          PRETTIER_OPTIONS: '--write'
          WORKING_DIRECTORY: '/backend'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ matrix.node-version }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: npm install

      - name: Run build script (if present)
        run: npm run build || echo "Build script not found."

      - name: Run tests (if present)
        run: npm test || echo "Test script not found."
